import numpy

# Main Loop Constants
LOOP_DELAY = 0.001

# Camera Constants
CAMERA_RESOLUTION = (320, 240)
CAMERA_FRAMERATE = 120
CAMERA_SHUTTER_SPEED = 20000
CAMERA_ISO = 800
CAMERA_INIT_TIME = 0.1

# Image Constants
IMAGE_FORMAT_BGR = "bgr"
IMAGE_OUTPUT_DIMENSION = (1080, 720)
IMAGE_EDGES_LOW_THRESHOLD = 50
IMAGE_EDGES_HIGH_THRESHOLD = 100
IMAGE_EDGES_APERTURE_SIZE = 3
IMAGE_HOUGHLINES_RHO = 1
IMAGE_HOUGHLINES_THETA = numpy.pi / 180
IMAGE_HOUGHLINES_THRESHOLD = 100
IMAGE_HOUGHLINES_MIN_LINE_LENGTH = 1
IMAGE_HOUGHLINES_MAX_LINE_GAP = 20
IMAGE_HOUGHLINES_COLOR = (255, 0, 0)
IMAGE_HOUGHLINES_THICKNESS = 2

# Debug Server Constants
RPI_IP_ADDRESS = "192.168.0.194"
RPI_PORT = 9999
MAX_CONNECIONS = 1
SEGMENT_FORMAT = "L"
RECEIVED_SEGMENT_SIZE = 4 * 1024
CLOSE_SERVER_KEY = 'q'